FROM node:10

# Create app directory
WORKDIR /srv/**DOCKER_SRC_PATH**

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm build
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE **DOCKER_PORT**
CMD ["npm",  "run", "dev" ]#
