name: Template CI

on: [push]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 3.0

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Check lint
        run: npm run lint

      # - name: Check tests
      #   run: npm run test:ci
      #   env:
      #     REDIS_URL: 'redis://127.0.0.1:6379'
